language: elixir
sudo: false
notifications:
  email: false

elixir:
  - 1.7
  - 1.8

otp_release:
  - 21.1
  - 21.2

script:
  - make testing

cache:
  directories:
    - _build
    - deps
    - priv/plts

after_script:
  - make docs
after_success:
  - bash <(curl -s https://codecov.io/bash)
