language: elixir
sudo: false
notifications:
  email: false

elixir:
  - 1.7
  - 1.8

otp_release:
  - 21.1
  - 21.2
  
before_cache:
  - rm -rf _build/$MIX_HOME/lib

cache:
  directories:
    - _build/$MIX_HOME

before_script:
  - travis_wait mix dialyzer --plt

script:
  - make testing

after_script:
  - make docs

after_success:
  - bash <(curl -s https://codecov.io/bash)
